### PR TITLE
Descriptions added by tool

### PR DESCRIPTION
**Pull request by ghogen**
Also includes some manual post-tool cleanup work and a TOC typo fix

### CODE REVIEW

**Comment by ghogen** [comment]
@Mikejo5000 can we also remove the reference to "whitelist" in the sample in ci-guide.md ?

**Comment by Mikejo5000** [comment]
@ghogen If we can just remove that whole line from the sample, that would be best.

**Comment by ghogen** [comment]
@Mikejo5000 Please review and merge if OK.

**Review by Mikejo5000 — APPROVED** [review]

**Comment by Mikejo5000** [comment]
Thanks, Gordon. Looks good to me!

**Pull request merged**
